# Generated by Django 4.2.7 on 2023-12-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(default='91', help_text='Country code', max_length=10)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.PositiveBigIntegerField(blank=True, null=True)),
                ('alt_mobile', models.PositiveBigIntegerField(blank=True, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('primary_language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Tamil', 'Tamil'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Punjabi', 'Punjabi'), ('Malayalam', 'Malayalam'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu')], help_text='Primary language of the user', max_length=10, null=True)),
                ('secondary_language', models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Tamil', 'Tamil'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Punjabi', 'Punjabi'), ('Malayalam', 'Malayalam'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu')], help_text='Secondary language of the user', max_length=10, null=True)),
                ('blitz_user', models.BooleanField(default=False)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.CharField(blank=True, help_text='Last login details for website api', max_length=40, null=True)),
                ('forgot_password_code', models.CharField(blank=True, max_length=255, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_user', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('fb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_user', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('email_support', models.BooleanField(default=True)),
                ('sms_support', models.BooleanField(default=False)),
                ('whatsapp_support', models.BooleanField(default=False)),
                ('sap_account_id', models.BigIntegerField(blank=True, null=True)),
                ('sf_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sf_customer_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=255, null=True)),
                ('referred_by', models.IntegerField(blank=True, null=True)),
                ('account_notifications', models.CharField(default='0', help_text='1- My project, 2 - Cart, 3 - Both, 0 - None', max_length=255)),
                ('logged_in_hlstore', models.BooleanField(default=False)),
                ('otp_retry_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('expiry_email_enabled', models.BooleanField(default=True, help_text='Enable expiry email for customer')),
            ],
            options={
                'indexes': [models.Index(fields=['sf_account_id', 'is_deleted'], name='core_custom_sf_acco_2d5f23_idx'), models.Index(fields=['sf_customer_account_id'], name='core_custom_sf_cust_ac2876_idx'), models.Index(fields=['mobile', 'is_deleted'], name='core_custom_mobile_090d1d_idx')],
            },
        ),
    ]
