# Generated by Django 4.2.7 on 2023-12-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backbonecustomerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='actual_move_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='actual_possession_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='alternate_appointment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='appointment_fixed_date',
            field=models.DateTimeField(blank=True, help_text='to store appointment_fixed_date_time__c from salesforce webhook', null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='appointment_fixed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='area_code',
            field=models.IntegerField(blank=True, default=91),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='artifact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='assigned_to_resi_asm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='auto_number_for_quote_creation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='blockers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='budget_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='builder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='builder_name_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='builtup_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='cc_office',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='channel_partner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='chat_app',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='chat_app_user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='check_in_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='current_lead_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='customer_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='customer_overall_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='customer_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='customer_property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='date_of_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='dead_lead_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='design_partner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='design_partner_sf_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='en_sc_options',
            field=models.BooleanField(blank=True, default=True, help_text='Enable SC options Pop up before SC Launch or not'),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='estimate_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='extra_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='first_home',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='first_meeting_completed_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='first_meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='floorplan_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='floorplan_received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='floorplan_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='follow_up_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='freelancer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='gst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='hds',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='hl_referrer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='how_did_you_hear_about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='how_likely_will_you_recommend_sc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='installation_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='installation_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='interior_designer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='interior_rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='interior_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='is_design_required',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='last_open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='lead_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='lead_or_opportunity_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='lead_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='lose_furniture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='loss_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='lost_opp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='main_order_sf_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='meeting_counter_in_stage_0_10',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='meeting_counter_in_stage_10_40',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='meeting_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='meeting_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='meeting_start_time',
            field=models.DateTimeField(blank=True, help_text='Meeting start time', null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='meeting_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='modular_storage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='move_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='nearest_showroom_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='new_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='new_opportunity_Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='new_opportunity_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='nps_additional_feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='nps_answers_percentage_40',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='nps_comments_percentage_40',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='nps_feedback_question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='nps_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='nps_percentage_40',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='nps_percentage_40_signoff_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='nps_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='offer_proposed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='opp_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='opportunity_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='opportunity_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='opportunity_sub_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='order_book_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='order_closed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='owner_sfid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='past_project_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='possession',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='possession_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='priority_lead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='priority_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='probability',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='probability_of_closure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='probability_of_closure_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='property_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='property_config',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='property_modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='property_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='property_name_sfid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='property_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='property_type_of_home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='purpose_of_interiors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='qualified_lead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='quote_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='quote_reviewed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='quote_sent_DP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='quote_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='rainSCVM',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='reach_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='referral_dp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='regional_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='renovation_services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='request_call_back',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='requested_callback',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='res_visit_venue_acceptance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='res_visit_venue_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='res_visit_venue_landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='res_visit_venue_locality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='res_visit_venue_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='res_visit_venue_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='residence_visit_offered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='residence_visit_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='rv_flow_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='rv_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sales_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sales_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sales_manager_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sc_launch_flag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sc_pro_launch_flag',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sc_recommended_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='scope_of_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='second_meeting_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='second_meeting_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='second_meeting_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='second_meeting_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='send_emailv2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='send_whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sf_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='showroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='showroom_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='showroom_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='showroom_sfid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sign_up_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sm_assigned_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='stage_flow',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='star_rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='sub_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='time_of_actual_appointment_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='total_quote_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='type_of_meeting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='user_rv_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='user_sf_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='wardrobe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='warranty_document_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='what_did_you_like_most',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='when_is_the_customer_planning_to_visit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='wt_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='wt_agent_allocated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backbonecustomerinfo',
            name='wt_agent_sfid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
