# Generated by Django 4.2.7 on 2023-12-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_backbonecustomerinfo_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, help_text='city of user should not be empty', max_length=255, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('installation_city_id', models.IntegerField(default=0)),
                ('country', models.IntegerField(blank=True, help_text='Country id from country table', null=True)),
                ('secondary_email', models.CharField(blank=True, max_length=255, null=True)),
                ('alternate_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('group_id', models.IntegerField(default=7)),
                ('opportunity_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sm_menu', models.TextField(blank=True, help_text='For session menu for menu builders', null=True)),
                ('sitemax_roles', models.CharField(default='user', max_length=750)),
                ('company', models.BooleanField(default=2, help_text='1-capricoast,2-homelane')),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('zoho_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sf_lead_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sf_opportunity_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sf_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.CharField(blank=True, help_text='Customer ID is generated in the zoho', max_length=255, null=True)),
                ('parent_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_pro', models.BooleanField(blank=True, help_text='This flag is used to determine if Customer is Pro or Not', null=True)),
                ('meeting_nps_question_id', models.IntegerField(blank=True, null=True)),
                ('meeting_nps_complete', models.BooleanField(default=False)),
                ('brand', models.IntegerField(default=1, help_text='FK of brands table')),
                ('lead_creation_stage', models.CharField(blank=True, choices=[('10-40', '10-40')], max_length=5, null=True)),
                ('type_of_order', models.CharField(choices=[('customer', 'customer'), ('showroom', 'showroom')], default='customer', max_length=8)),
                ('customer_profile_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customerprofile')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.backbonecustomerinfo')),
            ],
            options={
                'indexes': [models.Index(fields=['sf_lead_id'], name='core_user_sf_lead_4e9667_idx'), models.Index(fields=['sf_opportunity_id'], name='core_user_sf_oppo_c08002_idx'), models.Index(fields=['customer_id'], name='core_user_custome_bca3c0_idx'), models.Index(fields=['company'], name='core_user_company_795953_idx'), models.Index(fields=['user_id', 'company', 'is_deleted'], name='core_user_user_id_444427_idx'), models.Index(fields=['user_id', 'is_deleted'], name='email_no_delete'), models.Index(fields=['modified_on'], name='modified_idx'), models.Index(fields=['customer_profile_id', 'is_deleted'], name='core_user_custome_a7682e_idx'), models.Index(fields=['meeting_nps_question_id'], name='core_user_meeting_d02007_idx'), models.Index(fields=['brand'], name='core_user_brand_01740a_idx')],
            },
        ),
    ]
