# Generated by Django 4.2.7 on 2023-12-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('showroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_id', models.IntegerField()),
                ('showroom_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=225, null=True)),
                ('city', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, default=0, null=True)),
                ('district', models.IntegerField(blank=True, default=None, null=True)),
                ('pincode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sales_district', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('sales_group', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('booking_type', models.SmallIntegerField(blank=True, default=0, help_text='1-physical,2-virtual,3-both,0-none', null=True)),
                ('appointment_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('banner_image', models.CharField(blank=True, default=None, help_text='Banner images for landingpage desktop', max_length=255, null=True)),
                ('banner_image_mobile', models.CharField(blank=True, default=None, help_text='Banner images for landingpage mobile', max_length=255, null=True)),
                ('site_cleaning_po', models.BooleanField(default=True)),
                ('calendar_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fsm_calendar_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default=' ', max_length=15, null=True)),
                ('sales_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('showroom_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('design_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('installation_manager', models.CharField(blank=True, help_text='comma separate values and it will ref user id', max_length=255, null=True)),
                ('secondary_phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('contact_person', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('contact_mobile', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('contact_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('showroom_timings', models.TextField(blank=True, default=None, help_text='for showroom timings', null=True)),
                ('zoho_id', models.CharField(blank=True, default=None, help_text='Showroom id in Zoho', max_length=255, null=True)),
                ('live_sf_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sand_sf_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('login_code', models.CharField(blank=True, default=None, help_text='login code for showroom users', max_length=255, null=True)),
                ('type', models.SmallIntegerField(blank=True, default=1, help_text='1=>Showroom; 2=>Offices; 3=>Offices and Showroom; 4=>Squarelet', null=True)),
                ('google_review_place_id', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('url_3d', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_coworkingspace', models.BooleanField(blank=True, default=False, help_text='To indicate a coworking space showroom', null=True)),
                ('is_deleted', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.IntegerField(blank=True, default=None, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.IntegerField(blank=True, default=None, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, default=None, null=True)),
                ('opened_days', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cluster_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('brand', models.IntegerField(blank=True, default=1, help_text='1- homelane, 2 doowup, 3- pronto', null=True)),
            ],
            options={
                'db_table': 'showrooms',
            },
        ),
    ]
