# Generated by Django 4.2.7 on 2023-12-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_showroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackboneCustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('dp_id', models.PositiveIntegerField(blank=True, help_text='DP ID for the customer', null=True)),
                ('is_curated_dp', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', help_text='Is the DP a curated DP?', max_length=3)),
                ('dp_selection_reason', models.CharField(blank=True, help_text='Reason for selecting Non curated DP', max_length=255, null=True)),
                ('is_new_dp', models.BooleanField(blank=True, null=True)),
                ('jdp_id', models.IntegerField(blank=True, null=True)),
                ('sc_id', models.IntegerField(blank=True, null=True)),
                ('installation_showroom_id', models.IntegerField(blank=True, null=True)),
                ('pm_id', models.PositiveIntegerField(blank=True, help_text='Project Manager ID for the customer', null=True)),
                ('sm_id', models.PositiveIntegerField(blank=True, help_text='Iron Man ID for the customer', null=True)),
                ('cm_id', models.IntegerField(blank=True, help_text='Community Manager ID for the customer', null=True)),
                ('captain_id', models.IntegerField(blank=True, help_text='Captain ID for the customer', null=True)),
                ('sales_manager_id', models.IntegerField(blank=True, help_text='Sales Manager ID for the customer', null=True)),
                ('im_id', models.IntegerField(blank=True, help_text='Installation Manager ID for the customer', null=True)),
                ('dm_id', models.IntegerField(blank=True, help_text='Delivery Manager ID for the customer', null=True)),
                ('csr_id', models.IntegerField(blank=True, null=True)),
                ('si_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referral_sqp_franchise_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('mmt_id', models.IntegerField(blank=True, null=True)),
                ('install_qc_id', models.IntegerField(blank=True, null=True)),
                ('bm_id', models.IntegerField(blank=True, help_text='Business Manager ID for the customer', null=True)),
                ('pc_id', models.IntegerField(blank=True, help_text='Product Consultant ID for the customer', null=True)),
                ('dsm_id', models.IntegerField(blank=True, help_text='Doowup Sales Manager ID for the Customer', null=True)),
                ('dealer', models.IntegerField(blank=True, null=True)),
                ('dealer_designer', models.IntegerField(blank=True, null=True)),
                ('cust_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('showroom_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.showroom')),
            ],
            options={
                'db_table': 'backbone_customer_event',
            },
        ),
    ]
