# Generated by Django 4.2.7 on 2023-12-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_showroom_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.IntegerField(choices=[(1, 'capricoast'), (2, 'homelane')], default=2, help_text='1-capricoast, 2-homelane'),
        ),
    ]
