# Generated by Django 4.2.7 on 2023-12-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerprofile'),
        ),
    ]
