# Generated by Django 4.2.7 on 2023-12-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_customer_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backbonecustomerevent',
            name='showroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.showroom'),
        ),
    ]
