# Generated by Django 4.2.7 on 2023-12-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_backbonecustomerevent_showroom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backbonecustomerevent',
            old_name='cust_id',
            new_name='user_id',
        ),
    ]
