# Generated by Django 4.2.7 on 2023-12-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_cust_id_backbonecustomerevent_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backbonecustomerevent',
            old_name='user_id',
            new_name='cust_id',
        ),
    ]
